### PR TITLE
Implementation FlatTriangulation::operator+(vectors)

### LINKED ISSUE #145: Support surface + vectors
> Typically I want to do surface + v where v is a std::vector<flatsurf.Vector<T>> of size the number of edges in the surface. The operation means replace the vector h associated to edge e with h + v[e.index()].

### PR DESCRIPTION
**Pull request by saraedum**
fixes #145

TODO:

* [x] Implement what's written in `Following Tangent Vectors`.

### CODE REVIEW

**Comment by saraedum** [comment]
I am struggling with https://bitbucket.org/wlav/cppyy/issues/166/cast-instance-before-it-enters-python#comment-56725114 here. Otherwise I get random segfaults. Let's see if upstream cppyy has some idea how to fix this.

**Comment by videlec** [comment]
It would be nice if the implementation would also handle the following degenerate scenario. For some choice of vectors `(v1, ..., vn)` we might end up with edges of length zero. However, this is a perfectly well defined surface as long as in any triangle in the initial surface there is at most one degenerating edge.

This is very similar to the collapsed edges that you had to deal with for `FlowDecomposition`.

**Comment by saraedum** [comment]
So should that face just be dropped completely from the surface in that case? Or should it still be tracked somehow?

**Comment by videlec** [comment]
We don't want to carry the information in the new surface. However, we want as part of the output the relabeling that occurred in the degeneration. That is the map "half edge in the new surface" -> "half edge in the old surface". When no degeneration occurr, this is just the identity map. Maybe `operator+` is not best suited for this degenerate case because we want a pair as output.

**Comment by saraedum** [comment]
Could be a non-const version of `operator+` which performs the relabeling on the original surface...not overly pretty but this would allow us to extract the relabeling information.

**Comment by saraedum** [comment]
An `operator+` can of course also return a pair of things. But maybe we should just not call it `operator+` anymore.

**Comment by videlec** [comment]
Maybe this should be implemented as a distinct function then.

**Comment by videlec** [comment]
For implementing degenerations, see #176

**Pull request merged**
