### PR TITLE
Tests for complete periodicity and parabolicity

### PR DESCRIPTION
**Pull request by videlec**
Add method to `FlowDecomposition`/`FlowComponent` for testing complete periodicity and parabolicity.

(depends on https://github.com/flatsurf/intervalxt/pull/97)

### CODE REVIEW

**Comment by videlec** [comment]
Apparently, the tests do not use a recent enough version of `sage-flatsurf`
```
>       S = sage_flatsurf.translation_surfaces.mcmullen_genus2_prototype(4,2,1,1,QQ((1,4)))
E       AttributeError: 'TranslationSurfaceGenerators' object has no attribute 'mcmullen_genus2_prototype'
```
How could this be updated?

**Comment by saraedum** [comment]
> Apparently, the tests do not use a recent enough version of `sage-flatsurf`
> 
> ```
> >       S = sage_flatsurf.translation_surfaces.mcmullen_genus2_prototype(4,2,1,1,QQ((1,4)))
> E       AttributeError: 'TranslationSurfaceGenerators' object has no attribute 'mcmullen_genus2_prototype'
> ```
> 
> How could this be updated?

Easiest would be to make a sage-flatsurf release and update the upstream conda package.

**Comment by videlec** [comment]
relase 0.2 available at https://pypi.org/project/sage-flatsurf/

**Comment by videlec** [comment]
Everything is now Sage agnostic.

**Comment by videlec** [comment]
Is there a way to relaunch the tests with https://github.com/flatsurf/intervalxt/pull/97?

**Comment by saraedum** [comment]
Click Re-Run on the first one here: 
image

**Comment by videlec** [comment]
Could we merge this one?

**Comment by saraedum** [comment]
> Could we merge this one?

Absolutely, thanks :)

**Pull request merged**
