### PR TITLE
fix colinearity check in parabolic

### LINKED ISSUE #200: bug with parabolic
There is something wrong with the `parabolic()` method. The following example is the decagon surface with 7 additional marked points (in the stratum `H(2, 0^7)`). When we remove the 7 marked points it is a Veech surface. But with the marked point it is not.
```
sage: T = polygons.triangle(2, 3, 5)
sage: S = similarity_surfaces.billiard(T)
sage: S = S.minimal_cover(cover_type="translation")
sage: O = GL2ROrbitClosure(S)
sage: all(dec.decomposition.parabolic() == True for dec in O.decompositions_depth_first(3, 50))   # should be False
True
```

### PR DESCRIPTION
**Pull request by videlec**
Fixes #200

### CODE REVIEW

**Comment by videlec** [comment]
hmm. Surprising consequence
```
parabolic.test.cc:40
...............................................................................

parabolic.test.cc:40: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  *surface := FlatTriangulationCombinatorial(vertices = (1, -3, 8, -7, 3, -2,
  4, -6, 2, -1, 9, -8, 7, -9, 5, -4, 6, -5), faces = (1, 2, 3)(-1, -5, -9)(-2,
  -6, -4)(-3, -7, -8)(4, 5, 6)(7, 8, 9)) with vectors 1: (1, (x ~ 1.7320508)),
  2: (-1, 0), 3: (0, (-x ~ -1.7320508)), 4: (1, 1), 5: (-1, 0), 6: (0, -1), 7:
  ((x-1 ~ 0.73205081), (x ~ 1.7320508)), 8: ((-x+1 ~ -0.73205081), 0), 9: (0,
  (-x ~ -1.7320508))
  flowDecomposition := FlowDecompsition(components=[Component with perimeter [
  (-1, (-x ~ -1.7320508)) from -1 to 1 → (1, 0) from -5 to 5 → ((x-1 ~ 0.
  73205081), 0) from -8 to 8 → (1, (x ~ 1.7320508)) from 1 to -1 → (-1, 0)
  from 2 to -2 → ((-x+1 ~ -0.73205081), 0) from 8 to -8], Component with
  perimeter [(-1, -1) from -4 to 4 → (1, 0) from -2 to 2 → (1, 1) from 4 to
  -4 → (-1, 0) from 5 to -5]])
  SIGSEGV - Segmentation violation signal
```

**Comment by videlec** [comment]
@saraedum How did you generate the examples in `libflatsurf/test/surfaces.hpp`? I would like to use the surface obtained by unfolding the (2, 3, 5) triangle.

**Comment by saraedum** [comment]
> @saraedum How did you generate the examples in `libflatsurf/test/surfaces.hpp`? I would like to use the surface obtained by unfolding the (2, 3, 5) triangle.

I created them somewhat manually looking at the `to_pyflatsurf` output. Let me try to add that one to `surfaces.hpp` here.

**Comment by saraedum** [comment]
> hmm. Surprising consequence

```
==23541== Invalid read of size 4
==23541==    at 0x5649ECB: __gmpq_mul (in /tmp/ruth/miniconda/envs/flatsurf-build/lib/libgmp.so.10.4.0)
==23541==    by 0x4DC72CB: eval (gmpxx.h:539)
==23541==    by 0x4DC72CB: eval (gmpxx.h:2403)
==23541==    by 0x4DC72CB: __gmp_set_expr<__gmp_binary_expr<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_binary_multiplies> > (gmpxx.h:2248)
==23541==    by 0x4DC72CB: __gmp_expr<__gmp_binary_expr<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_binary_multiplies> > (gmpxx.h:1804)
==23541==    by 0x4DC72CB: operator!=<__mpq_struct [1], __gmp_binary_expr<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_binary_multiplies>, __mpq_struct [1], __gmp_binary_expr<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_binary_multiplies> > (gmpxx.h:3331)
==23541==    by 0x4DC72CB: flatsurf::FlowDecomposition<flatsurf::FlatTriangulation<eantic::renf_elem_class> >::parabolic() const (flow_decomposition.cc:156)
==23541==    by 0x11C816: flatsurf::test::____C_A_T_C_H____T_E_S_T____0() (parabolic.test.cc:52)
==23541==    by 0x11F89A: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14054)
==23541==    by 0x12300D: Catch::TestCase::invoke() const (catch.hpp:13947)
==23541==    by 0x12302D: Catch::RunContext::invokeActiveTestCase() (catch.hpp:12809)
==23541==    by 0x13AAAA: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12782)
==23541==    by 0x13ADF8: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12543)
==23541==    by 0x14711C: execute (catch.hpp:13137)
==23541==    by 0x14711C: Catch::Session::runInternal() (catch.hpp:13343)
==23541==    by 0x1473E2: Catch::Session::run() (catch.hpp:13299)
==23541==    by 0x1474E3: run<char> (catch.hpp:13021)
==23541==    by 0x1474E3: main (catch.hpp:17182)
==23541==  Address 0x7225ef4 is 4 bytes after a block of size 32 alloc'd
==23541==    at 0x4836E3F: operator new(unsigned long) (vg_replace_malloc.c:344)
==23541==    by 0x4DBF43B: allocate (new_allocator.h:111)
==23541==    by 0x4DBF43B: allocate (alloc_traits.h:436)
==23541==    by 0x4DBF43B: _M_allocate (stl_vector.h:172)
==23541==    by 0x4DBF43B: void std::vector<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, std::allocator<__gmp_expr<__mpq_struct [1], __mpq_struct [1]> > >::_M_realloc_insert<__gmp_expr<__mpq_struct [1], __mpq_struct [1]> const&>(__gnu_cxx::__normal_iterator<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>*, std::vector<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, std::allocator<__gmp_expr<__mpq_struct [1], __mpq_struct [1]> > > >, __gmp_expr<__mpq_struct [1], __mpq_struct [1]> const&) (vector.tcc:406)
==23541==    by 0x4DBF704: push_back (stl_vector.h:948)
==23541==    by 0x4DBF704: intervalxt::sample::Arithmetic<eantic::renf_elem_class, void>::coefficients(eantic::renf_elem_class const&) (e-antic-arithmetic.hpp:40)
==23541==    by 0x4DC72A5: flatsurf::FlowDecomposition<flatsurf::FlatTriangulation<eantic::renf_elem_class> >::parabolic() const (flow_decomposition.cc:154)
==23541==    by 0x11C816: flatsurf::test::____C_A_T_C_H____T_E_S_T____0() (parabolic.test.cc:52)
==23541==    by 0x11F89A: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14054)
==23541==    by 0x12300D: Catch::TestCase::invoke() const (catch.hpp:13947)
==23541==    by 0x12302D: Catch::RunContext::invokeActiveTestCase() (catch.hpp:12809)
==23541==    by 0x13AAAA: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12782)
==23541==    by 0x13ADF8: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12543)
==23541==    by 0x14711C: execute (catch.hpp:13137)
==23541==    by 0x14711C: Catch::Session::runInternal() (catch.hpp:13343)
==23541==    by 0x1473E2: Catch::Session::run() (catch.hpp:13299)
```

**Comment by videlec** [comment]
But this is not clear that this invalid read is actually the cause of the SEGFAULT, is it?

**Comment by videlec** [comment]
Under gdb I got the following backtrace (apparently pointing to the same thing as valgrind)
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6808da2 in __gmpn_gcd_1 () from /home/vincent/miniconda3/envs/sage-flatsurf/lib/./libgmp.so.10
(gdb) bt
#0  0x00007ffff6808da2 in __gmpn_gcd_1 () from /home/vincent/miniconda3/envs/sage-flatsurf/lib/./libgmp.so.10
#1  0x00007ffff67d0b75 in __gmpz_gcd () from /home/vincent/miniconda3/envs/sage-flatsurf/lib/./libgmp.so.10
#2  0x00007ffff67de02a in __gmpq_mul () from /home/vincent/miniconda3/envs/sage-flatsurf/lib/./libgmp.so.10
#3  0x00007ffff7d799a8 in __gmp_binary_multiplies::eval (s=<optimized out>, r=<optimized out>, q=0x7fffffffc390) at /usr/local/src/conda-prefix/include/gmpxx.h:539
#4  __gmp_expr<__mpq_struct [1], __gmp_binary_expr<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_binary_multiplies> >::eval (p=0x7fffffffc390, 
    this=<optimized out>) at /usr/local/src/conda-prefix/include/gmpxx.h:2403
#5  __gmp_set_expr<__gmp_binary_expr<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_binary_multiplies> > (expr=..., q=0x7fffffffc390)
    at /usr/local/src/conda-prefix/include/gmpxx.h:2248
#6  __gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr<__gmp_binary_expr<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_binary_multiplies> > (
    expr=..., this=0x7fffffffc390) at /usr/local/src/conda-prefix/include/gmpxx.h:1804
#7  operator!=<__mpq_struct [1], __gmp_binary_expr<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_binary_multiplies>, __mpq_struct [1], __gmp_binary_expr<__gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_expr<__mpq_struct [1], __mpq_struct [1]>, __gmp_binary_multiplies> > (expr2=..., expr1=...) at /usr/local/src/conda-prefix/include/gmpxx.h:3331
#8  flatsurf::FlowDecomposition<flatsurf::FlatTriangulation<eantic::renf_elem_class> >::parabolic (this=<optimized out>) at flow_decomposition.cc:156
#9  0x000055555556adbf in flatsurf::test::____C_A_T_C_H____T_E_S_T____0() ()
#10 0x0000555555575741 in Catch::RunContext::invokeActiveTestCase() ()
#11 0x000055555559bc37 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#12 0x00005555555a8886 in Catch::RunContext::runTest(Catch::TestCase const&) ()
#13 0x00005555555b0272 in Catch::Session::runInternal() ()
#14 0x00005555555b08eb in Catch::Session::run() ()
#15 0x0000555555563767 in main ()
```

**Comment by videlec** [comment]
In your commit, the embedding of the base ring is different from the one I get with `sage-flatsurf`
```
sage: from flatsurf import polygons, similarity_surfaces
sage: similarity_surfaces.billiard(polygons.triangle(2, 3, 5)).minimal_cover(cover_type="translation").base_ring()
Number Field in c with defining polynomial x^4 - 5*x^2 + 5 with c = 1.902113032590308?
```
whereas you use
```
P = renf_class::make("x^4 - 5*x^2 + 5", "x", "1.17557050 +/- .1")
```
As a consequence, the directions in my tests for `(2, 3, 5)` are the wrong ones. Coud you confirm that the surface you considered is still the correct one.

**Comment by saraedum** [comment]
> As a consequence, the directions in my tests for (2, 3, 5) are the wrong ones. Coud you confirm that the surface you considered is still the correct one.
You are absolutely right. I just looked at the minpoly but the embedding does not match actually.

**Comment by saraedum** [comment]
Do you know how to fix it or should I push  a fix?

**Comment by videlec** [comment]
It does not seem that `P` is used anywhere else. I have a branch that simply changes the embedding. Still the tests do not pass for the `(2, 3, 5)` triangle.

**Comment by saraedum** [comment]
Why don't they pass? (I'm on Zulip if you want to discuss this.)

**Comment by videlec** [comment]
There is a problem with the direction `(1, 0)` in the `(2, 3, 5)` triangle. This is supposed to be parabolic (4 cylinders which have exactly the same modulus).

**Comment by videlec** [comment]
All right. Better now!

**Pull request merged**
