### PR TITLE
Integrate with intervalxt

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
Requires https://github.com/flatsurf/intervalxt/pull/22.

**Comment by saraedum** [comment]
Requires https://github.com/flatsurf/intervalxt/pull/23

**Comment by videlec** [comment]
```
libtool: compile:  g++ -std=gnu++11 -std=gnu++17 -DHAVE_CONFIG_H -I. -I../../src -g -O2 -MT permutation.lo -MD -MP -MF .deps/permutation.Tpo -c permutation.cc  -fPIC -DPIC -o .libs/permutation.o
length_along_triangulation.cc: In member function 'flatsurf::LengthAlongTriangulation<T>::Quotient flatsurf::LengthAlongTriangulation<T>::operator/(const flatsurf::LengthAlongTriangulation<T>&)':
length_along_triangulation.cc:203:105: error: 'class exactreal::Arb' has no member named 'floor'
   mpz_class quo = static_cast<Arb>((impl->approximation / rhs.impl->approximation)(ARB_PRECISION_FAST)).floor();
```
I guess the changes to exact real have to be merged... I have no way to test anything currently

**Comment by saraedum** [comment]
Needs https://github.com/flatsurf/exact-real/pull/47.

**Pull request merged**
